// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp94qf3OwJKSHTh6UiZFYMktOj_C1MIb0',
    appId: '1:396808102799:web:d9ff74e9b0a1ba1b1661fa',
    messagingSenderId: '396808102799',
    projectId: 'fuel-station-demo-app',
    authDomain: 'fuel-station-demo-app.firebaseapp.com',
    storageBucket: 'fuel-station-demo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMZ1evu0MCXfp86D00TZ82vAhjv7WNjAM',
    appId: '1:396808102799:android:1755362805b3c1691661fa',
    messagingSenderId: '396808102799',
    projectId: 'fuel-station-demo-app',
    storageBucket: 'fuel-station-demo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp94qf3OwJKSHTh6UiZFYMktOj_C1MIb0',
    appId: '1:396808102799:web:d9ff74e9b0a1ba1b1661fa',
    messagingSenderId: '396808102799',
    projectId: 'fuel-station-demo-app',
    authDomain: 'fuel-station-demo-app.firebaseapp.com',
    storageBucket: 'fuel-station-demo-app.firebasestorage.app',
    iosBundleId: 'com.rk.fuels.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp94qf3OwJKSHTh6UiZFYMktOj_C1MIb0',
    appId: '1:396808102799:web:d9ff74e9b0a1ba1b1661fa',
    messagingSenderId: '396808102799',
    projectId: 'fuel-station-demo-app',
    authDomain: 'fuel-station-demo-app.firebaseapp.com',
    storageBucket: 'fuel-station-demo-app.firebasestorage.app',
    iosBundleId: 'com.rk.fuels.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp94qf3OwJKSHTh6UiZFYMktOj_C1MIb0',
    appId: '1:396808102799:web:d9ff74e9b0a1ba1b1661fa',
    messagingSenderId: '396808102799',
    projectId: 'fuel-station-demo-app',
    authDomain: 'fuel-station-demo-app.firebaseapp.com',
    storageBucket: 'fuel-station-demo-app.firebasestorage.app',
  );
}
