// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PEafiRB1Ia9HtWOOWAshismVQF1aVNQ',
    appId: '1:62828412342:web:60157e768ae8c9ace95517',
    messagingSenderId: '62828412342',
    projectId: 'rk-fuels-app-2026',
    authDomain: 'rk-fuels-app-2026.firebaseapp.com',
    storageBucket: 'rk-fuels-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKy1Cn4xkNQ_ZeNq04aIG9wZ43x_1a78',
    appId: '1:62828412342:android:90cccfce4660330ae95517',
    messagingSenderId: '62828412342',
    projectId: 'rk-fuels-app-2026',
    storageBucket: 'rk-fuels-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FBmKngNkVmDIjmObkW3hlaCvkI-wvUY',
    appId: '1:62828412342:ios:6072393fc3203956e95517',
    messagingSenderId: '62828412342',
    projectId: 'rk-fuels-app-2026',
    storageBucket: 'rk-fuels-app-2026.firebasestorage.app',
    iosBundleId: 'com.rk.fuels.rkFuels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-FBmKngNkVmDIjmObkW3hlaCvkI-wvUY',
    appId: '1:62828412342:ios:6072393fc3203956e95517',
    messagingSenderId: '62828412342',
    projectId: 'rk-fuels-app-2026',
    storageBucket: 'rk-fuels-app-2026.firebasestorage.app',
    iosBundleId: 'com.rk.fuels.rkFuels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-PEafiRB1Ia9HtWOOWAshismVQF1aVNQ',
    appId: '1:62828412342:web:21f35f64bb5d373ce95517',
    messagingSenderId: '62828412342',
    projectId: 'rk-fuels-app-2026',
    authDomain: 'rk-fuels-app-2026.firebaseapp.com',
    storageBucket: 'rk-fuels-app-2026.firebasestorage.app',
  );
}
